// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract DiplomaRegistry {

   
    struct Diploma {
        bytes32 certId;        // An id generated by the contract for each certi
        string  studentId;     // Student number 
        string  studentName;   // Full name
        string  schoolName;    // Issuing school name
        string  degreeName;    // Master , ingenieur ...
        string  fieldOfStudy;  // Mi , St ...
        string  ipfsHash;      // An id generated by the ipfs service of the html diploma
        uint256 issueDate;     // Unix timestamp
        address issuedBy;      // School wallet that issued it
        bool    isRevoked;     //Is deleted or not
    }

   //setters (poo vibes)
    address public owner;

    mapping(bytes32 => Diploma)    private diplomas;
    mapping(string  => bytes32[])  private studentDiplomas;
    mapping(address => bool)       public  authorizedSchools;
    mapping(address => string)     public  schoolNames;
    mapping(string  => mapping(string => bool)) private alreadyIssued;

    uint256 private nonce; // this one is a cool variable that changes for each diploma making the hash unique for every and each one thus the cid has to be unique

    //some random events

    event SchoolAuthorized(address indexed school, string name);
    event SchoolRevoked(address indexed school);
    event DiplomaIssued(bytes32 indexed certId, string studentId, address indexed school, string degreeName);
    event DiplomaRevoked(bytes32 indexed certId, address revokedBy);
//some checking up logique (checks if the data is right )
    
    modifier onlyOwner() {
        require(msg.sender == owner, "Not the contract owner");
        _;
    }

    modifier onlyAuthorizedSchool() {
        require(authorizedSchools[msg.sender], "Not an authorized school");
        _;
    }

    modifier diplomaExists(bytes32 certId) {
        require(diplomas[certId].issueDate != 0, "Diploma does not exist");
        _;
    }

   // a constructor , this is a function called only once to set the initial variable , its like a one time setter for anyone reading the code
    constructor() {
        owner = msg.sender;
    }

    //super admin stuff , sets up allowed schools and removes em

    function authorizeSchool(address school, string calldata name) external onlyOwner {
        require(school != address(0), "Invalid address");
        require(!authorizedSchools[school], "School already authorized");
        authorizedSchools[school] = true;
        schoolNames[school] = name;
        emit SchoolAuthorized(school, name);
    }

    function revokeSchoolAuthorization(address school) external onlyOwner {
        require(authorizedSchools[school], "School is not authorized");
        authorizedSchools[school] = false;
        emit SchoolRevoked(school);
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Invalid address");
        owner = newOwner;
    }

  //school work , aka admin.

    function issueDiploma(
        string calldata studentId,
        string calldata studentName,
        string calldata degreeName,
        string calldata fieldOfStudy,
        string calldata ipfsHash
    ) external onlyAuthorizedSchool returns (bytes32 certId) {
        require(bytes(studentId).length > 0,   "Student ID required");
        require(bytes(studentName).length > 0, "Student name required");
        require(bytes(degreeName).length > 0,  "Degree name required");
        require(!alreadyIssued[studentId][degreeName] || _isRevoked(studentId, degreeName), "An active diploma already exists for this degree");

        certId = keccak256(abi.encodePacked(studentId, msg.sender, block.timestamp, nonce));
        nonce++;

        diplomas[certId] = Diploma({
            certId:       certId,
            studentId:    studentId,
            studentName:  studentName,
            schoolName:   schoolNames[msg.sender],
            degreeName:   degreeName,
            fieldOfStudy: fieldOfStudy,
            ipfsHash:     ipfsHash,
            issueDate:    block.timestamp,
            issuedBy:     msg.sender,
            isRevoked:    false
        });

        studentDiplomas[studentId].push(certId);
        alreadyIssued[studentId][degreeName] = true;

        emit DiplomaIssued(certId, studentId, msg.sender, degreeName);
    }
 function _isRevoked(string calldata studentId, string calldata degreeName) internal view returns (bool) {
    bytes32[] storage ids = studentDiplomas[studentId];
    for (uint256 i = 0; i < ids.length; i++) {
        Diploma storage d = diplomas[ids[i]];
        if (keccak256(bytes(d.degreeName)) == keccak256(bytes(degreeName)) && !d.isRevoked) {
            return false; // found an active one → not revoked
        }
    }
    return true; // all existing ones are revoked → allow reissue
}
    function revokeDiploma(bytes32 certId) external diplomaExists(certId) {
        Diploma storage d = diplomas[certId];
        require(!d.isRevoked, "Diploma already revoked");
        require(msg.sender == owner || msg.sender == d.issuedBy, "Not authorized to revoke");
        d.isRevoked = true;
        alreadyIssued[d.studentId][d.degreeName] = false;
        emit DiplomaRevoked(certId, msg.sender);
    }
 event DiplomaUnrevoked(bytes32 indexed certId, address unrevokedBy);

 function unrevokeDiploma(bytes32 certId) external diplomaExists(certId) {
    Diploma storage d = diplomas[certId];
    require(d.isRevoked, "Diploma is not revoked");
    require(msg.sender == owner || msg.sender == d.issuedBy, "Not authorized to unrevoke");
    d.isRevoked = false;
    emit DiplomaUnrevoked(certId, msg.sender);
}
    function getDiploma(bytes32 certId) external view diplomaExists(certId) returns (Diploma memory) {
        return diplomas[certId];
    }

    function getStudentDiplomas(string calldata studentId) external view returns (bytes32[] memory) {
        return studentDiplomas[studentId];
    }

    function verifyDiploma(bytes32 certId) external view returns (bool) {
        Diploma storage d = diplomas[certId];
        if (d.issueDate == 0) return false;
        return !d.isRevoked;
    }

    function getDiplomaCount(string calldata studentId) external view returns (uint256) {
        return studentDiplomas[studentId].length;
    }
}
